2024-05-26 23:39:23.164630: I tensorflow_serving/model_servers/server.cc:77] Building single TensorFlow model file config:  model_name: my_model model_base_path: /tmp/tfsrver/models/my_model/
2024-05-26 23:39:23.171147: I tensorflow_serving/model_servers/server_core.cc:471] Adding/updating models.
2024-05-26 23:39:23.171405: I tensorflow_serving/model_servers/server_core.cc:600]  (Re-)adding model: my_model
2024-05-26 23:39:23.173879: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:24.173972: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:25.174066: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:26.174153: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:27.174255: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:28.174357: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:29.174448: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:30.174545: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:31.174639: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:32.174769: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:33.174862: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:34.174953: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:35.175074: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:36.175157: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:37.175262: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:38.175363: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:39.175460: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:40.175526: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:41.175633: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:42.175722: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:43.176974: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:44.177115: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:45.177223: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:46.177368: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:47.177494: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:48.177586: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:49.177710: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:50.177823: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:51.177948: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:52.178072: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:53.178162: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:54.178259: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:55.178354: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:56.178455: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:57.178542: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:58.178662: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:39:59.178741: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:00.178869: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:01.179017: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:02.179161: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:03.179213: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:04.179326: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:05.179405: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:06.179496: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:07.179573: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:08.179725: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:09.179810: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:10.179902: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:11.180034: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:12.180121: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:13.180217: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:14.180301: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:15.180383: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:16.180476: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:17.180556: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:18.180649: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:19.180731: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:20.180856: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:21.180969: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:22.181057: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:23.181135: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:24.181211: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:25.181310: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:26.181447: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:27.181536: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:28.181620: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:29.181708: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:30.181841: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:31.181888: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:32.181986: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:33.182092: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:34.182225: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:35.184380: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:36.184469: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:37.184564: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:38.184661: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:39.184768: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:40.184828: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:41.184957: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:42.185084: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:43.185204: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:44.185316: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:45.185437: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:46.185503: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:47.185603: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:48.185775: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:49.185855: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:50.186036: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:51.186135: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:52.186270: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:53.186383: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:54.186524: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:55.186680: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:56.186767: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:57.186857: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:58.187036: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:40:59.187162: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:00.187243: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:01.187357: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:02.187475: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:03.187586: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:04.187714: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:05.187799: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:06.187917: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:07.188017: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:08.188148: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:09.188242: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:10.188365: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:11.188529: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:12.188614: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:13.188702: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:14.188787: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:15.188887: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:16.188990: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:17.189127: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:18.189207: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:19.189288: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:20.189376: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:21.189478: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:22.189569: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:23.189687: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:24.189784: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:25.189871: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:26.189966: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:27.190067: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:28.190218: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:29.192808: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:30.192928: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:31.193005: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:32.193111: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:33.193185: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:34.193276: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:35.193385: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:36.193470: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:37.193579: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:38.193692: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:39.193778: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:40.193876: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:41.193991: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:42.194072: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:43.194217: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:44.194309: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:45.194407: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:46.194512: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:47.194655: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:48.194740: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:49.194846: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:50.194975: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:51.195093: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:52.195259: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:53.195311: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:54.195433: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:55.195554: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:56.195660: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:57.195753: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:58.195864: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:41:59.195965: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:00.196071: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:01.196170: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:02.196292: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:03.196425: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:04.196538: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:05.196642: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:06.196757: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:07.196863: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:08.196994: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:09.197114: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:10.197202: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:11.197326: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:12.197432: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:13.197528: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:14.197612: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:15.197736: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:16.197836: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:17.197969: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:18.198062: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:19.198158: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:20.198293: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:21.198410: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:22.198532: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:23.198655: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:24.198753: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:25.198859: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:26.198971: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:27.199059: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:28.199180: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:29.199238: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:30.199267: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:31.199357: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:32.199447: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:33.199532: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:34.199627: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:35.199712: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:36.199812: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:37.199924: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:38.200013: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:39.200116: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:40.200207: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:41.200322: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:42.200407: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:43.200512: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:44.200604: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:45.200701: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:46.200817: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:47.200906: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:48.201011: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:49.201095: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:50.201182: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:51.201285: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:52.201377: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:53.201458: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:54.201546: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:55.201622: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:56.201704: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:57.201805: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:58.201905: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:42:59.202005: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:00.202106: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:01.202197: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:02.202304: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:03.202394: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:04.202726: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:05.202568: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:06.202696: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:07.202796: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:08.202896: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:09.203025: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:10.203156: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:11.203236: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:12.203340: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:13.203461: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:14.203545: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:15.203679: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:16.203793: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:17.203878: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:18.204069: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:19.204164: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:20.204284: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:21.204408: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:22.204504: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:23.204690: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:24.204796: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:25.204919: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:26.205011: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:27.205138: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:28.205250: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:29.205369: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:30.205496: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:31.205607: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:32.205710: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:33.205810: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:34.205928: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:35.206042: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:36.206133: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:37.206289: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:38.206382: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:39.206481: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:40.206570: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:41.206692: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:42.206775: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:43.206873: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:44.206999: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:45.207108: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:46.207243: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:47.207392: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:48.207485: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:49.207613: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:50.207708: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:51.207851: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:52.207966: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:53.208091: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:54.208222: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:55.208322: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:56.208441: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:57.208514: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:58.208634: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:43:59.208769: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:00.208894: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:01.209009: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:02.209123: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:03.209275: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:04.209354: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:358] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /tmp/tfsrver/models/my_model/ for servable my_model with error NOT_FOUND: /tmp/tfsrver/models/my_model/ not found
2024-05-26 23:44:05.355888: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: my_model version: 1}
2024-05-26 23:44:05.356155: I tensorflow_serving/core/loader_harness.cc:68] Approving load for servable version {name: my_model version: 1}
2024-05-26 23:44:05.356378: I tensorflow_serving/core/loader_harness.cc:76] Loading servable version {name: my_model version: 1}
2024-05-26 23:44:05.392543: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tfsrver/models/my_model/1
2024-05-26 23:44:05.403679: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:51] Reading meta graph with tags { serve }
2024-05-26 23:44:05.403959: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:146] Reading SavedModel debug info (if present) from: /tmp/tfsrver/models/my_model/1
2024-05-26 23:44:05.536585: I external/org_tensorflow/tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
2024-05-26 23:44:05.545403: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:234] Restoring SavedModel bundle.
2024-05-26 23:44:05.716531: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:218] Running initialization op on SavedModel bundle at path: /tmp/tfsrver/models/my_model/1
2024-05-26 23:44:05.724831: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:317] SavedModel load for tags { serve }; Status: success: OK. Took 339672 microseconds.
2024-05-26 23:44:05.725801: I tensorflow_serving/servables/tensorflow/saved_model_warmup_util.cc:82] No warmup data file found at /tmp/tfsrver/models/my_model/1/assets.extra/tf_serving_warmup_requests
2024-05-26 23:44:05.826644: I tensorflow_serving/core/loader_harness.cc:97] Successfully loaded servable version {name: my_model version: 1}
2024-05-26 23:44:05.837350: I tensorflow_serving/model_servers/server_core.cc:492] Finished adding/updating models
2024-05-26 23:44:05.838960: I tensorflow_serving/model_servers/server.cc:121] Using InsecureServerCredentials
2024-05-26 23:44:05.845820: I tensorflow_serving/model_servers/server.cc:388] Profiler service is enabled
2024-05-26 23:44:05.922985: I tensorflow_serving/model_servers/server.cc:423] Running gRPC ModelServer at 0.0.0.0:8500 ...
2024-05-26 23:44:05.947745: I tensorflow_serving/model_servers/server.cc:444] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 250] NET_LOG: Entering the event loop ...
2024-05-26 23:45:43.470792: W external/org_tensorflow/tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: FAILED_PRECONDITION: Could not find variable dense/bias. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/dense/bias/N10tensorflow3VarE does not exist.
	 [[{{function_node __inference_serving_default_577}}{{node sequential_1/dense_1/Add/ReadVariableOp}}]]
2024-05-26 23:45:43.471106: W external/org_tensorflow/tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: ABORTED: Stopping remaining executors.
